### PR TITLE
Adds onboarding presentation to In Cluster Team

### PR DESCRIPTION
**Pull request by JoaoBraveCoding**
New members must get to know these details as it helps them understand what our culture is and how things work. It not only gives identity to the team but also defines key interactions that otherwise would be open to interpretation/guessing.

### CODE REVIEW

**Comment by bwplotka** [comment]
Probably some of this content could go to prv Google Doc we can link here to hide personal information. cc @danielm0hr

**Comment by jan--f** [comment]
Yeah I'd vote to integrate this with what we have already. And +1 for hiding personal information. In fact @JoaoBraveCoding can you remove the team chart please ;)

**Comment by JoaoBraveCoding** [comment]
I've removed the org chart, however, I believe it's an important piece of information for a new member. If this presentation contains sensitive information I would be more in favour of keeping it in Google Drive and linking it here.

I'm also up to moving some of the content to the onboarding doc but I feel it already has a lot of information. Furthermore, the goal of this presentation was to not only cover some information which is not common to both teams but also to cover some dynamic information like what happened in the last few sprints that it would be useful/insightful for the person to know.

**Comment by bwplotka** [comment]
Thanks a lot. Unfortunately, I don't think many would use the special tooling to access that information. I feel it would be more accessible as one pager with multiple sections 🙈

**Pull request closed without merging**
